rules:
  unpinned-uses:
    config:
      policies:
        "dtolnay/rust-toolchain": ref-pin
  cache-poisoning:
    ignore:
      - ci.yml:34
      - ci.yml:82
      - ci.yml:112
      - ci.yml:143
      - ci.yml:179
  dangerous-triggers:
    ignore:
      - release-plz.yml